//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.DCMLRACPGProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "DCMLRACPG_ProyIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"DCMLRACPGProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DCMLRACPGProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DCMLRACPGProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DCMLRACPGProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DCMLRACPGProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDCMLRACPGProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DCMLRACPGProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string DCMLRACPGProyectoIPSPackageId = "864bdef2-a50a-4d37-a1d8-9f2398d80509";
		
		// Editor factory identifier
		public const string DCMLRACPGProyectoIPSEditorFactoryId = "74060ce3-65a4-418f-9013-79ed1166bd5c";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DCMLRACPGProyectoIPSModelExplorerToolWindowId = "a16e949e-8cba-4406-a66b-fc6da5e5bf4d";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.DCMLRACPGProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DCMLRACPGProyectoIPSCommandSetId = "e08af248-9c04-4439-93d1-84d01f8193d3";
	}
}